name: lumen
description: AI Chat & Multimodal Assistant
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.6.0
  http_parser: ^4.1.2
  path: ^1.9.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  photo_manager: ^3.3.0
  path_provider: ^2.1.5
  file_picker: ^10.3.7
  shared_preferences: ^2.5.4
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.1
  lucide_icons_flutter: ^3.1.13
  intl: ^0.20.2
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.2
  flutter_markdown: ^0.7.4+1
  video_player: ^2.9.2
  chewie: ^1.8.5
  gal: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/image/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/language/
    - assets/image/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Light.ttf
          weight: 300
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
