export type LanguageOption = {
  code: string;       // ISO 639-1
  name: string;       // English name
  nativeName: string; // Name in that language
  direction: "ltr" | "rtl";
};

export const LANGUAGES: LanguageOption[] = [
  { code: "af", name: "Afrikaans",             nativeName: "Afrikaans",             direction: "ltr" },
  { code: "sq", name: "Albanian",              nativeName: "Shqip",                 direction: "ltr" },
  { code: "am", name: "Amharic",               nativeName: "አማርኛ",                 direction: "ltr" },
  { code: "ar", name: "Arabic",                nativeName: "العربية",               direction: "rtl" },
  { code: "hy", name: "Armenian",              nativeName: "Հայերեն",               direction: "ltr" },
  { code: "az", name: "Azerbaijani",           nativeName: "Azərbaycan",            direction: "ltr" },
  { code: "eu", name: "Basque",                nativeName: "Euskara",               direction: "ltr" },
  { code: "be", name: "Belarusian",            nativeName: "Беларуская",            direction: "ltr" },
  { code: "bn", name: "Bengali",               nativeName: "বাংলা",                 direction: "ltr" },
  { code: "bs", name: "Bosnian",               nativeName: "Bosanski",              direction: "ltr" },
  { code: "bg", name: "Bulgarian",             nativeName: "Български",             direction: "ltr" },
  { code: "ca", name: "Catalan",               nativeName: "Català",                direction: "ltr" },
  { code: "zh", name: "Chinese (Simplified)",  nativeName: "中文 (简体)",            direction: "ltr" },
  { code: "zh-TW", name: "Chinese (Traditional)", nativeName: "中文 (繁體)",         direction: "ltr" },
  { code: "hr", name: "Croatian",              nativeName: "Hrvatski",              direction: "ltr" },
  { code: "cs", name: "Czech",                 nativeName: "Čeština",               direction: "ltr" },
  { code: "da", name: "Danish",                nativeName: "Dansk",                 direction: "ltr" },
  { code: "nl", name: "Dutch",                 nativeName: "Nederlands",            direction: "ltr" },
  { code: "en", name: "English",               nativeName: "English",               direction: "ltr" },
  { code: "et", name: "Estonian",              nativeName: "Eesti",                 direction: "ltr" },
  { code: "fi", name: "Finnish",               nativeName: "Suomi",                 direction: "ltr" },
  { code: "fr", name: "French",                nativeName: "Français",              direction: "ltr" },
  { code: "gl", name: "Galician",              nativeName: "Galego",                direction: "ltr" },
  { code: "ka", name: "Georgian",              nativeName: "ქართული",               direction: "ltr" },
  { code: "de", name: "German",                nativeName: "Deutsch",               direction: "ltr" },
  { code: "el", name: "Greek",                 nativeName: "Ελληνικά",              direction: "ltr" },
  { code: "gu", name: "Gujarati",              nativeName: "ગુજરાતી",               direction: "ltr" },
  { code: "he", name: "Hebrew",                nativeName: "עברית",                 direction: "rtl" },
  { code: "hi", name: "Hindi",                 nativeName: "हिन्दी",                direction: "ltr" },
  { code: "hu", name: "Hungarian",             nativeName: "Magyar",                direction: "ltr" },
  { code: "is", name: "Icelandic",             nativeName: "Íslenska",              direction: "ltr" },
  { code: "id", name: "Indonesian",            nativeName: "Bahasa Indonesia",      direction: "ltr" },
  { code: "ga", name: "Irish",                 nativeName: "Gaeilge",               direction: "ltr" },
  { code: "it", name: "Italian",               nativeName: "Italiano",              direction: "ltr" },
  { code: "ja", name: "Japanese",              nativeName: "日本語",                 direction: "ltr" },
  { code: "kn", name: "Kannada",               nativeName: "ಕನ್ನಡ",                  direction: "ltr" },
  { code: "kk", name: "Kazakh",                nativeName: "Қазақша",               direction: "ltr" },
  { code: "km", name: "Khmer",                 nativeName: "ខ្មែរ",                  direction: "ltr" },
  { code: "ko", name: "Korean",                nativeName: "한국어",                  direction: "ltr" },
  { code: "ky", name: "Kyrgyz",                nativeName: "Кыргызча",              direction: "ltr" },
  { code: "lo", name: "Lao",                   nativeName: "ລາວ",                   direction: "ltr" },
  { code: "lv", name: "Latvian",               nativeName: "Latviešu",              direction: "ltr" },
  { code: "lt", name: "Lithuanian",            nativeName: "Lietuvių",              direction: "ltr" },
  { code: "mk", name: "Macedonian",            nativeName: "Македонски",            direction: "ltr" },
  { code: "ms", name: "Malay",                 nativeName: "Bahasa Melayu",         direction: "ltr" },
  { code: "ml", name: "Malayalam",             nativeName: "മലയാളം",                direction: "ltr" },
  { code: "mt", name: "Maltese",               nativeName: "Malti",                 direction: "ltr" },
  { code: "mr", name: "Marathi",               nativeName: "मराठी",                 direction: "ltr" },
  { code: "mn", name: "Mongolian",             nativeName: "Монгол",                direction: "ltr" },
  { code: "ne", name: "Nepali",                nativeName: "नेपाली",                direction: "ltr" },
  { code: "nb", name: "Norwegian",             nativeName: "Norsk",                 direction: "ltr" },
  { code: "fa", name: "Persian",               nativeName: "فارسی",                 direction: "rtl" },
  { code: "pl", name: "Polish",                nativeName: "Polski",                direction: "ltr" },
  { code: "pt", name: "Portuguese",            nativeName: "Português",             direction: "ltr" },
  { code: "pt-BR", name: "Portuguese (Brazil)", nativeName: "Português (Brasil)",   direction: "ltr" },
  { code: "pa", name: "Punjabi",               nativeName: "ਪੰਜਾਬੀ",                direction: "ltr" },
  { code: "ro", name: "Romanian",              nativeName: "Română",                direction: "ltr" },
  { code: "ru", name: "Russian",               nativeName: "Русский",               direction: "ltr" },
  { code: "sr", name: "Serbian",               nativeName: "Српски",                direction: "ltr" },
  { code: "si", name: "Sinhala",               nativeName: "සිංහල",                 direction: "ltr" },
  { code: "sk", name: "Slovak",                nativeName: "Slovenčina",            direction: "ltr" },
  { code: "sl", name: "Slovenian",             nativeName: "Slovenščina",           direction: "ltr" },
  { code: "es", name: "Spanish",               nativeName: "Español",               direction: "ltr" },
  { code: "sw", name: "Swahili",               nativeName: "Kiswahili",             direction: "ltr" },
  { code: "sv", name: "Swedish",               nativeName: "Svenska",               direction: "ltr" },
  { code: "tl", name: "Tagalog",               nativeName: "Tagalog",               direction: "ltr" },
  { code: "ta", name: "Tamil",                 nativeName: "தமிழ்",                  direction: "ltr" },
  { code: "te", name: "Telugu",                nativeName: "తెలుగు",                 direction: "ltr" },
  { code: "th", name: "Thai",                  nativeName: "ภาษาไทย",               direction: "ltr" },
  { code: "tr", name: "Turkish",               nativeName: "Türkçe",                direction: "ltr" },
  { code: "uk", name: "Ukrainian",             nativeName: "Українська",            direction: "ltr" },
  { code: "ur", name: "Urdu",                  nativeName: "اردو",                  direction: "rtl" },
  { code: "uz", name: "Uzbek",                 nativeName: "O'zbek",                direction: "ltr" },
  { code: "vi", name: "Vietnamese",            nativeName: "Tiếng Việt",            direction: "ltr" },
  { code: "cy", name: "Welsh",                 nativeName: "Cymraeg",               direction: "ltr" },
  { code: "xh", name: "Xhosa",                 nativeName: "isiXhosa",              direction: "ltr" },
  { code: "yi", name: "Yiddish",               nativeName: "יידיש",                 direction: "rtl" },
  { code: "yo", name: "Yoruba",                nativeName: "Yorùbá",                direction: "ltr" },
  { code: "zu", name: "Zulu",                  nativeName: "isiZulu",               direction: "ltr" },
];

export function getLanguageByCode(code: string): LanguageOption | undefined {
  return LANGUAGES.find((l) => l.code === code);
}
